Changaco/python-libarchive-c

libarchive/ffi.py
Support c_ssize_t in python 2.6
Python 2.6 currently was not in the test plan(https://github.com/Changaco/python-libarchive-c/blob/master/.travis.yml#L26), this patch just a workaround
close #36
=> Support c_ssize_t in python 2.6

libarchive/ffi.py, libarchive/write.py, tests/test_rwx.py
Add new method `add_entry_from_memory` for creating archive from files stored in memory.
=> Add new method to ArchiveWrite- add_entry_from_memory

libarchive/ffi.py
While working with large files I found out that if entry is bigger than > 3.5 GB there is error in type- int is too small.
=> Change c_int to c_longlong for entry_set_size

libarchive/write.py, setup.cfg
Check if file is symlink before opening.
=> fix ArchiveWrite.add_files() chokes on broken symlinks

tox.ini
pytest-xdist has a nice mode, --boxed, that along with running tests in
a separate subprocess, can also report on crashes due to libarchive
library misuse.
This allows pytest runs to detect libarchive segfaults and give us
better feedback when we misuse the C API via ctypes.
More information: https://pypi.python.org/pypi/pytest-xdist#boxed
=> Add xdist for segfault detection

libarchive/ffi.py
This just exposes the `read_support_` functions for lz4/warc, which I find useful for checking if my library was compiled with support for the formats.
=> Add read/write support for LZ4 and WARC

libarchive/__init__.py, libarchive/ffi.py, libarchive/read.py, tests/test_rwx.py
It is fairly typical for Python file objects to be used on the read side
of archive processing. For instance, io.BufferedReader and similar
API that handles I/O itself.
To allow for libarchive interaction with these objects, we need a
custom_reader that can use the `readinto()` style access to the raw
archive data. `readinto()` is used as that allows us to read the data
into a `ctypes.create_string_buffer()` structure and easily cast the
pointers for the read callback. The preallocated buffer also ensures
that libarchive gets access to contiguous memory and that buffer isn't
garbage collected by Python after the callback returns.
=> Add custom_reader for archives

README.rst, setup.cfg
It took me too long to figure out why this thing wasn't working out of the box, and Googling around, it seems a lot of people have been facing similar issues. Hoping that with these few extra documentation lines, that pain is gone.
=> Adds some notes to make libarchive work on MacOS 10.14

.travis.yml, tests/__init__.py, tox.ini
>           mode = tarfile.filemode(entry.mode)[1:]
E           AttributeError: module 'tarfile' has no attribute 'filemode'
=> Python 3.8: tarfile.filemode is gone, use stat.filemode if available

libarchive/entry.py
Defining `__slots__` improves memory usage and speed.
=> Optimize the `ArchiveEntry` class

libarchive/ffi.py
Currently a warning level log message is produced for each read/write format and filter that's not available. This adds to log clutter and can trigger automated alerts. These should be informational messages.
Fixes #74
=> Reduce unnecessary log noise

libarchive/ffi.py
Anaconda has been carrying this in their build of libarchive-c for a while:
https://github.com/AnacondaRecipes/python-libarchive-c-feedstock/tree/master/recipe
=> Add zstd support

libarchive/write.py, tests/test_rwx.py
=> Enhance add_file_from_memory

libarchive/write.py, tests/test_rwx.py
Currently, any file entry added using `add_file_from_memory()` is saved with uninformative epoch-zero timestamps.
This is a backward-compatible enhancement designed to allow the user to add timestamps of their choosing to archives created with this method, without cumbersome workarounds, patches, or code forks.
Closes #73
=> Allow timestamps for add_file_from_memory

libarchive/ffi.py, libarchive/read.py, libarchive/write.py
This commit modifies `new_archive_read` and `new_archive_write` to automatically look up the format and filter initialization functions if they haven't been loaded by default.
=> Load extra formats and filters when they're requested

libarchive/ffi.py, libarchive/read.py, libarchive/write.py, setup.cfg
=> Reading and writing encrypted archives

tests/test_rwx.py, tox.ini
Remove the obsolete six dependency from `tox.ini`, and replace the external `mock` backport with built-in `unittest.mock` that's present since Python 3.3.
=> Remove obsolete dependencies

setup.py, version.py
Thanks for `python-libarchive-c`, and congratulations on 4.0! 
This tries to read `PKG-INFO` as `utf-8` to avoid situations like this, encountered downstream on [conda-forge](https://github.com/conda-forge/python-libarchive-c-feedstock/pull/31) ([log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=445520&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=3cc4a9ed-60e1-5810-6eb3-5f9cd4a26dba&l=323)): 
```py
Processing d:\bld\python-libarchive-c_1642883867449\work\dist
Added file:///D:/bld/python-libarchive-c_1642883867449/work/dist to build tracker 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-req-tracker-j2qxfoak'
Running setup.py (path:%SRC_DIR%\dist\setup.py) egg_info for package from file:///D:/bld/python-libarchive-c_1642883867449/work/dist
Created …
```
=> read PKG-INFO, README as utf-8

libarchive/entry.py
Add a default value for `timesatmap_nsec` to `set_atime()`, `set_mtime()`, and `set_ctime()`.  `set_birthtime()` already had this.
The corresponding setter properties only pass a single value if the time is just an int.
=> Add default value timestamp_nsec to set_{a,c,m}time

libarchive/entry.py, libarchive/read.py, tests/test_rwx.py
=> Fix `format_name` property and move it to `ArchiveRead`

tests/test_entry.py
=> Handle new libarchive versions

libarchive/write.py
add_files() sets destination_path to attributes['pathname']. However, add_files() also has a keyword parameter with the name 'pathname'. Because the keyword parameter 'pathname' exists, attributes['pathname'] is always None.
Correct the issue by using the pathname keyword argument instead of attributes['path'].
Fixes: issue #134
=> write.py: add_files() rm attributes['pathname']

README.rst, libarchive/ffi.py, libarchive/write.py, tests/test_rwx.py
Add bindings to change symlink read behavior. Unfortunately, libarchive does not seem to have a way of getting the current setting, so only the setter was implemented.
Closes: #132
Signed-off-by: Nicholas Vinson <nvinson234@gmail.com>
=> Add bindings to change symlink read behavior.

libarchive/entry.py, libarchive/ffi.py, tests/test_entry.py
Supersedes #136.
@nvinson Writing the digests doesn't actually work. https://github.com/libarchive/libarchive/pull/2540 wasn't enough, because the mtree writer only writes [the digests it has computed itself](https://github.com/libarchive/libarchive/blob/992a596290057695242558798b7929e0112e5b3d/libarchive/archive_write_set_format_mtree.c#L85), not [the ones stored in the archive entry](https://github.com/libarchive/libarchive/blob/992a596290057695242558798b7929e0112e5b3d/libarchive/archive_entry_private.h#L177).
=> Add read-write access to digests stored in archive entries
